CREATE PROCEDURE [dbo].[sp_GetEmp]
AS
SELECT A.EMPL, A.EMPLNAME

FROM (

        SELECT RTRIM(VALUE) AS EMPL, RTRIM(VDESC) EMPLNAME, CASE WHEN VALUE = 'COM' THEN 9 WHEN VALUE = 'KDH' THEN 1 ELSE 2 END SORT

        FROM CSOPTFD

        WHERE OPTFIELD = 'EMPL'

) A

ORDER BY A.SORT, A.EMPL
Go