/* 경영 계획기존 데이터가 없다면*/
CREATE PROCEDURE [dbo].[sp_ManagementSub_SelInit]
		@YYYY Char(4) =''
AS
Select * from 
(
    Select
        0 as itype												,
        ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS rownum		,
        a.Idx													,
        0 as Num									,
        a.UserId												,
        RTRIM(c.VDESC) as UserName								,
        a.CusttomerCode											,
        a.CusttomerName											,
        '' servion												,     
        0 as p1													,
        0 as r1													,
        0 as p2													,
        0 as r2													,
        0 as p3													,
        0 as r3													,
        0 as q1p													,
        0 as q1r													,
        0 as p4													,
        0 as r4													,
        0 as p5													,
        0 as r5													,
        0 as p6													,
        0 as r6													,
        0 as q2p													,
        0 as q2r													,
        0 as s1p													,
        0 as s1r													,
        0 as p7													,
        0 as r7													,
        0 as p8													,
        0 as r8													,
        0 as p9													,
        0 as r9													,
        0 as q3p													,
        0 as q3r													,
        0 as p10													,
        0 as r10													,
        0 as p11													,
        0 as r11													,
        0 as p12													,
        0 as r12													,
        0 as q4p													,
        0 as q4r													,
        0 as s2p													,
        0 as s2r													,
        0 as yp													,
        0 as yr													,
        0 as raw													,
        0 as ass													,
        0 as plp													,
        0 as plr													,
        0 as rusult
        from tb_ManagementMaster a 
        left join  CSOPTFD c  on a.UserId=RTRIM(c.VALUE)
        Where a.YYYY =@YYYY        
        and  OPTFIELD = 'EMPL'

		union all

		
		Select
        0 as itype												,
        0  AS rownum		,
        0 as Idx													,
        0 as Num									,
        a.UserId												,
        '' as UserName								,
        '' as CusttomerCode											,
        'Sub Total:' CusttomerName											,
        '' servion												,     
        0 as p1													,
        0 as r1													,
        0 as p2													,
        0 as r2													,
        0 as p3													,
        0 as r3													,
        0 as q1p													,
        0 as q1r													,
        0 as p4													,
        0 as r4													,
        0 as p5													,
        0 as r5													,
        0 as p6													,
        0 as r6													,
        0 as q2p													,
        0 as q2r													,
        0 as s1p													,
        0 as s1r													,
        0 as p7													,
        0 as r7													,
        0 as p8													,
        0 as r8													,
        0 as p9													,
        0 as r9													,
        0 as q3p													,
        0 as q3r													,
        0 as p10													,
        0 as r10													,
        0 as p11													,
        0 as r11													,
        0 as p12													,
        0 as r12													,
        0 as q4p													,
        0 as q4r													,
        0 as s2p													,
        0 as s2r													,
        0 as yp													,
        0 as yr													,
        0 as raw													,
        0 as ass													,
        0 as plp													,
        0 as plr													,
        0 as rusult
        from tb_ManagementMaster a 
        Where a.YYYY =@YYYY 
		group by a.UserId

		union all 

		Select
        9 as itype												,
        0  AS rownum		,
        0 as Idx													,
        0 as Num									,
        'ZZZ' UserId												,
        'ZZZ' as UserName								,
        '' as CusttomerCode											,
        'Total:' CusttomerName											,
        '' servion												,     
        0 as p1													,
        0 as r1													,
        0 as p2													,
        0 as r2													,
        0 as p3													,
        0 as r3													,
        0 as q1p													,
        0 as q1r													,
        0 as p4													,
        0 as r4													,
        0 as p5													,
        0 as r5													,
        0 as p6													,
        0 as r6													,
        0 as q2p													,
        0 as q2r													,
        0 as s1p													,
        0 as s1r													,
        0 as p7													,
        0 as r7													,
        0 as p8													,
        0 as r8													,
        0 as p9													,
        0 as r9													,
        0 as q3p													,
        0 as q3r													,
        0 as p10													,
        0 as r10													,
        0 as p11													,
        0 as r11													,
        0 as p12													,
        0 as r12													,
        0 as q4p													,
        0 as q4r													,
        0 as s2p													,
        0 as s2r													,
        0 as yp													,
        0 as yr													,
        0 as raw													,
        0 as ass													,
        0 as plp													,
        0 as plr													,
        0 as rusult
)tab
order by UserId   Asc,CusttomerName ,itype DESC

Go