Create proc [dbo].[sp_ManagementSub_Ins]
	@Num				INT				=0	,
	@idx				int				=0	,
	@servion			int				=0	,
	@p1				varchar(10) ='0'	,
	@r1				varchar(10) ='0'	,
	@p2				varchar(10) ='0'	,
	@r2				varchar(10) ='0'	,
	@p3				varchar(10) ='0'	,
	@r3				varchar(10) ='0'	,
	@q1p			varchar(10) ='0'	,
	@q1r			varchar(10) ='0'	,
	@p4				varchar(10) ='0'	,
	@r4				varchar(10) ='0'	,
	@p5				varchar(10) ='0'	,
	@r5				varchar(10) ='0'	,
	@p6				varchar(10) ='0'	,
	@r6				varchar(10) ='0'	,
	@q2p			varchar(10) ='0'	,
	@q2r			varchar(10) ='0'	,
	@s1p			varchar(10) ='0'	,
	@s1r			varchar(10) ='0'	,
	@p7				varchar(10) ='0'	,
	@r7				varchar(10) ='0'	,
	@p8				varchar(10) ='0'	,
	@r8				varchar(10) ='0'	,
	@p9				varchar(10) ='0'	,
	@r9				varchar(10) ='0'	,
	@q3p			varchar(10) ='0'	,
	@q3r			varchar(10) ='0'	,
	@p10			varchar(10) ='0'	,
	@r10			varchar(10) ='0'	,
	@p11			varchar(10) ='0'	,
	@r11			varchar(10) ='0'	,
	@p12			varchar(10) ='0'	,
	@r12			varchar(10) ='0'	,
	@q4p			varchar(10) ='0'	,
	@q4r			varchar(10) ='0'	,
	@s2p			varchar(10) ='0'	,
	@s2r			varchar(10) ='0'	,
	@yp				varchar(10) ='0'	,
	@yr				varchar(10) ='0'	,
	@raw			varchar(10) ='0'	,
	@ass			varchar(10) ='0'	,
	@plp			varchar(10) ='0'	,
	@plr			varchar(10) ='0'	,
	@rusult			varchar(10) ='0'	
	
	
AS
If not exists (Select top 1 * from tb_ManagementSub Where idx =@idx and servion =@servion) 
	Begin
		insert tb_ManagementSub 
		(
			idx		,
			servion	,
			p1		,
			r1		,
			p2		,
			r2		,
			p3		,
			r3		,
			q1p		,
			q1r		,
			p4		,
			r4		,
			p5		,
			r5		,
			p6		,
			r6		,
			q2p		,
			q2r		,
			s1p		,
			s1r		,
			p7		,
			r7		,
			p8		,
			r8		,
			p9		,
			r9		,
			q3p		,
			q3r		,
			p10		,
			r10		,
			p11		,
			r11		,
			p12		,
			r12		,
			q4p		,
			q4r		,
			s2p		,
			s2r		,
			yp		,
			yr		,
			raw		,
			ass		,
			plp		,
			plr		,
			rusult	,
			RegDate
		)
		Values
		(
			@idx		,
			@servion	,
			CONVERT(decimal,@p1)			,
			CONVERT(decimal,@r1)			,
			CONVERT(decimal,@p2)			,
			CONVERT(decimal,@r2)			,
			CONVERT(decimal,@p3)			,
			CONVERT(decimal,@r3)			,
			CONVERT(decimal,@q1p)		,
			CONVERT(decimal,@q1r)		,
			CONVERT(decimal,@p4	)		,
			CONVERT(decimal,@r4	)		,
			CONVERT(decimal,@p5	)		,
			CONVERT(decimal,@r5	)		,
			CONVERT(decimal,@p6	)		,
			CONVERT(decimal,@r6	)		,
			CONVERT(decimal,@q2p)		,
			CONVERT(decimal,@q2r)		,
			CONVERT(decimal,@s1p)		,
			CONVERT(decimal,@s1r)		,
			CONVERT(decimal,@p7	)		,
			CONVERT(decimal,@r7	)		,
			CONVERT(decimal,@p8	)		,
			CONVERT(decimal,@r8	)		,
			CONVERT(decimal,@p9	)		,
			CONVERT(decimal,@r9	)		,
			CONVERT(decimal,@q3p)		,
			CONVERT(decimal,@q3r)		,
			CONVERT(decimal,@p10)		,
			CONVERT(decimal,@r10)		,
			CONVERT(decimal,@p11)		,
			CONVERT(decimal,@r11)		,
			CONVERT(decimal,@p12)		,
			CONVERT(decimal,@r12)		,
			CONVERT(decimal,@q4p)		,
			CONVERT(decimal,@q4r)		,
			CONVERT(decimal,@s2p)		,
			CONVERT(decimal,@s2r)		,
			CONVERT(decimal,@yp	)		,
			CONVERT(decimal,@yr	)		,
			CONVERT(decimal,@raw)		,
			CONVERT(decimal,@ass)		,
			CONVERT(decimal,@plp)		,
			CONVERT(decimal,@plr)		,
			CONVERT(decimal,@rusult)	,
			GETDATE()	
		)
	End
Else
	Begin
		update tb_ManagementSub set 
			--idx		=@idx		,
			--servion	=@servion	,
			p1		=CONVERT(decimal,@p1)		,
			r1		=CONVERT(decimal,@r1)		,
			p2		=CONVERT(decimal,@p2)		,
			r2		=CONVERT(decimal,@r2)		,
			p3		=CONVERT(decimal,@p3)		,
			r3		=CONVERT(decimal,@r3)		,
			q1p		=CONVERT(decimal,@q1p)		,
			q1r		=CONVERT(decimal,@q1r)		,
			p4		=CONVERT(decimal,@p4)		,
			r4		=CONVERT(decimal,@r4	)		,
			p5		=CONVERT(decimal,@p5	)		,
			r5		=CONVERT(decimal,@r5	)		,
			p6		=CONVERT(decimal,@p6	)		,
			r6		=CONVERT(decimal,@r6	)		,
			q2p		=CONVERT(decimal,@q2p)		,
			q2r		=CONVERT(decimal,@q2r)		,
			s1p		=CONVERT(decimal,@s1p)		,
			s1r		=CONVERT(decimal,@s1r)		,
			p7		=CONVERT(decimal,@p7	)		,
			r7		=CONVERT(decimal,@r7	)		,
			p8		=CONVERT(decimal,@p8	)		,
			r8		=CONVERT(decimal,@r8	)		,
			p9		=CONVERT(decimal,@p9	)		,
			r9		=CONVERT(decimal,@r9	)		,
			q3p		=CONVERT(decimal,@q3p)		,
			q3r		=CONVERT(decimal,@q3r)		,
			p10		=CONVERT(decimal,@p10)		,
			r10		=CONVERT(decimal,@r10)		,
			p11		=CONVERT(decimal,@p11)		,
			r11		=CONVERT(decimal,@r11)		,
			p12		=CONVERT(decimal,@p12)		,
			r12		=CONVERT(decimal,@r12)		,
			q4p		=CONVERT(decimal,@q4p)		,
			q4r		=CONVERT(decimal,@q4r)		,
			s2p		=CONVERT(decimal,@s2p)		,
			s2r		=CONVERT(decimal,@s2r)		,
			yp		=CONVERT(decimal,@yp	)		,
			yr		=CONVERT(decimal,@yr	)		,
			raw		=CONVERT(decimal,@raw)		,
			ass		=CONVERT(decimal,@ass)		,
			plp		=CONVERT(decimal,@plp)		,
			plr		=CONVERT(decimal,@plr)		,
			rusult	=CONVERT(decimal,@rusult)	,
			ModDate = GETDATE()
		Where idx		=@idx
			and servion	=@servion
	End

