CREATE table dbo.tb_ManagementSub(
	Num			int IDENTITY(1,1) NOT NULL,
	idx			int NOT NULL,
	servion		int NOT NULL,
	p1			decimal(7, 2) NULL,
	r1			decimal(7, 2) NULL,
	p2			decimal(7, 2) NULL,
	r2			decimal(7, 2) NULL,
	p3			decimal(7, 2) NULL,
	r3			decimal(7, 2) NULL,
	q1p			decimal(7, 2) NULL,
	q1r			decimal(7, 2) NULL,
	p4			decimal(7, 2) NULL,
	r4			decimal(7, 2) NULL,
	p5			decimal(7, 2) NULL,
	r5			decimal(7, 2) NULL,
	p6			decimal(7, 2) NULL,
	r6			decimal(7, 2) NULL,
	q2p			decimal(7, 2) NULL,
	q2r			decimal(7, 2) NULL,
	s1p			decimal(7, 2) NULL,
	s1r			decimal(7, 2) NULL,
	p7			decimal(7, 2) NULL,
	r7			decimal(7, 2) NULL,
	p8			decimal(7, 2) NULL,
	r8			decimal(7, 2) NULL,
	p9			decimal(7, 2) NULL,
	r9			decimal(7, 2) NULL,
	q3p			decimal(7, 2) NULL,
	q3r			decimal(7, 2) NULL,
	p10			decimal(7, 2) NULL,
	r10			decimal(7, 2) NULL,
	p11			decimal(7, 2) NULL,
	r11			decimal(7, 2) NULL,
	p12			decimal(7, 2) NULL,
	r12			decimal(7, 2) NULL,
	q4p			decimal(7, 2) NULL,
	q4r			decimal(7, 2) NULL,
	s2p			decimal(7, 2) NULL,
	s2r			decimal(7, 2) NULL,
	yp			decimal(7, 2) NULL,
	yr			decimal(7, 2) NULL,
	raw			decimal(7, 2) NULL,
	ass			decimal(7, 2) NULL,
	plp			decimal(7, 2) NULL,
	plr			decimal(7, 2) NULL,
	rusult		decimal(7, 2) NULL,
	RegDate		datetime NULL,
	ModDate		datetime NULL,
)