CREATE PROC [dbo].[SP_OZ3120_Cust_Detail]
	@sAR		VARCHAR(3),		-- AR처리여부(Yes / No)
	@sDocNo		VARCHAR(22),	-- 문서번호
	@iDocType	SMALLINT		-- 문서유형
AS


IF @sAR = 'Yes'
BEGIN

	IF @iDocType = 1
	BEGIN

		SELECT B.DETAILNUM AS LINENUM, CASE WHEN B.LINETYPE = 1 THEN RTRIM(B.ITEM) ELSE RTRIM(B.MISCCHARGE) END ITEM, RTRIM(B.[DESC]) AS ITEMNAME, B.QTYSHIPPED AS QTY, B.INVUNIT AS UNIT, B.UNITPRICE, B.EXTICOST AS COGS, B.EXTINVMISC AS AMOUNT
		FROM OEINVH A
		INNER JOIN OEINVD B ON A.INVUNIQ = B.INVUNIQ
		WHERE B.INVUNIQ IS NOT NULL
			AND A.INVNUMBER = @sDocNo
		ORDER BY B.LINENUM

	END
	ELSE
	BEGIN

		SELECT B.DETAILNUM AS LINENUM, CASE WHEN B.LINETYPE = 1 THEN RTRIM(B.ITEM) ELSE RTRIM(B.MISCCHARGE) END ITEM, RTRIM(B.[DESC]) AS ITEMNAME, B.QTYRETURN * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END AS QTY, B.CRDUNIT AS UNIT, B.UNITPRICE, B.EXTCCOST * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END AS COGS, B.EXTCRDMISC * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END AS AMOUNT
		FROM OECRDH A
		INNER JOIN OECRDD B ON A.CRDUNIQ = B.CRDUNIQ
		WHERE B.CRDUNIQ IS NOT NULL
			AND A.CRDNUMBER = @sDocNo
		ORDER BY B.LINENUM

	END
END
ELSE
BEGIN


	SELECT A.LINENUM, A.ITEM, A.ITEMNAME, SUM(A.QTY) AS QTY, A.UNIT, A.UNITPRICE, 0 AS COGS, SUM(A.AMOUNT) AS AMOUNT
	FROM (

		SELECT B.DETAILNUM AS LINENUM, CASE WHEN B.LINETYPE = 1 THEN RTRIM(B.ITEM) ELSE RTRIM(B.MISCCHARGE) END ITEM, RTRIM(B.[DESC]) AS ITEMNAME, B.QTYORDERED AS QTY, B.ORDUNIT AS UNIT, B.UNITPRICE, B.EXTINVMISC AS AMOUNT
		FROM OEORDH A
		LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
		WHERE B.ORDUNIQ IS NOT NULL AND CASE WHEN B.LINETYPE = 1 THEN B.QTYORDERED ELSE B.EXTINVMISC END <> 0
			AND A.ORDNUMBER = @sDocNo
		
		UNION ALL

		SELECT B.ORDDTLNUM AS LINENUM, CASE WHEN B.LINETYPE = 1 THEN RTRIM(B.ITEM) ELSE RTRIM(B.MISCCHARGE) END ITEM, RTRIM(B.[DESC]) AS ITEMNAME, B.QTYSHIPPED AS QTY, B.SHIUNIT AS UNIT, B.UNITPRICE, B.EXTSHIMISC AS AMOUNT
		FROM OESHIH	A
		LEFT OUTER JOIN OESHID B ON A.SHIUNIQ = B.SHIUNIQ
		WHERE B.SHIUNIQ IS NOT NULL AND NUMINVOICE = 0
			AND A.ORDNUMBER = @sDocNo

	) A
	GROUP BY A.LINENUM, A.ITEM, A.ITEMNAME, A.UNIT, A.UNITPRICE
	ORDER BY A.LINENUM

END
Go