CREATE PROC [dbo].[SP_OZ3120_Cust_Header]
	@sAR		VARCHAR(3),		-- AR처리여부(Yes / No)
	@sDocNo		VARCHAR(22),	-- 문서번호
	@iDocType	SMALLINT		-- 문서유형
AS


IF @sAR = 'Yes'
BEGIN

	IF @iDocType = 1
	BEGIN

		SELECT RTRIM(INVNUMBER) AS INVNUMBER, RTRIM(PONUMBER) AS CUSTPO, RTRIM(CUSTOMER) AS CUSTOMER, RTRIM(BILNAME) AS BILNAME, RTRIM(SHINUMBER) AS SHINUMBER, INVDATE,
			RTRIM([LOCATION]) AS [LOCATION], RTRIM(SHIPTO) AS SHIPTO, RTRIM(SHPNAME) AS SHPNAME, RTRIM([DESC]) AS DESCR, RTRIM(REFERENCE) AS REFERENCE
		FROM OEINVH
		WHERE INVNUMBER = @sDocNo

	END
	ELSE
	BEGIN

		SELECT RTRIM(A.CRDNUMBER) AS INVNUMBER, RTRIM(A.PONUMBER) AS CUSTPO, RTRIM(A.CUSTOMER) AS CUSTOMER, RTRIM(A.BILNAME) AS BILNAME, ISNULL(B.SHINUMBER, '') AS SHINUMBER, CRDDATE AS INVDATE,
			RTRIM(A.[LOCATION]) AS [LOCATION], RTRIM(A.SHIPTO) AS SHIPTO, RTRIM(A.SHPNAME) AS SHPNAME, RTRIM(A.[DESC]) AS DESCR, RTRIM(A.REFERENCE) AS REFERENCE
		FROM OECRDH A
		LEFT OUTER JOIN OEINVH B ON A.INVNUMBER = B.INVNUMBER
		WHERE A.CRDNUMBER = @sDocNo

	END
END
ELSE
BEGIN

	SELECT RTRIM(ORDNUMBER) AS INVNUMBER, RTRIM(PONUMBER) AS CUSTPO, RTRIM(CUSTOMER) AS CUSTOMER, RTRIM(BILNAME) AS BILNAME, '' AS SHINUMBER, ORDDATE AS INVDATE,
		RTRIM([LOCATION]) AS [LOCATION], RTRIM(SHIPTO) AS SHIPTO, RTRIM(SHPNAME) AS SHPNAME, RTRIM([DESC]) AS DESCR, RTRIM(REFERENCE) AS REFERENCE
	FROM OEORDH
	WHERE ORDNUMBER = (
		SELECT DISTINCT A.ORDNUMBER
		FROM (

			SELECT A.ORDNUMBER
			FROM OEORDH A
			LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
			WHERE B.ORDUNIQ IS NOT NULL AND CASE WHEN B.LINETYPE = 1 THEN B.QTYORDERED ELSE B.EXTINVMISC END <> 0
				AND A.ORDNUMBER = @sDocNo
		
			UNION ALL

			SELECT A.ORDNUMBER
			FROM OESHIH	A
			LEFT OUTER JOIN OESHID B ON A.SHIUNIQ = B.SHIUNIQ
			WHERE B.SHIUNIQ IS NOT NULL AND NUMINVOICE = 0 AND A.ORDNUMBER <> ''
				AND A.ORDNUMBER = @sDocNo

		) A
	)

END

Go