CREATE PROC [dbo].[SP_OZ3120_Cust_Items]
	@sDate_F  CHAR(8),		-- 매출일자_FROM
	@sDate_T  CHAR(8),		-- 매출일자_TO
	@sItem_F  VARCHAR(24),	-- 품목코드_FROM
	@sItem_T  VARCHAR(24)	-- 품목코드_TO
	,@pageNum	int =1				
	,@amount	int =10
	,@ExcelYn	Char(1) ='N'
AS

CREATE TABLE #SO (
	ORDUNIQ	DECIMAL(18, 0),
	ITEMNO	VARCHAR(24),
	ORDAMT	DECIMAL(18, 3)
)

INSERT INTO #SO (ORDUNIQ, ITEMNO, ORDAMT)
SELECT A.ORDUNIQ, CASE WHEN B.LINETYPE = 1 THEN RTRIM(B.ITEM) ELSE RTRIM(B.MISCCHARGE) END ITEM, CASE WHEN B.LINETYPE = 1 THEN (B.QTYBACKORD + B.QTYSHPTODT) * B.UNITPRICE ELSE EXTINVMISC END AS ORDAMT
FROM OEORDH A
LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
WHERE B.ORDUNIQ IS NOT NULL


if (@ExcelYn <> 'N')
Begin

	SELECT RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], MISC.[DESC])) AS ITEMDESC, A.ORDAMT, A.COGS, A.EXTINVMISC, A.AR, A.ARTYPE
	FROM (
		--Invoice
		SELECT A.ITEM, SUM(SO.ORDAMT) AS ORDAMT, SUM(A.EXTICOST) AS COGS, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AR, A.ARTYPE
		FROM (
			SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTICOST, B.EXTINVMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
			FROM OEINVH A
			LEFT OUTER JOIN OEINVD B ON A.INVUNIQ = B.INVUNIQ
			LEFT OUTER JOIN OEINVHO ARTYPE ON A.INVUNIQ = ARTYPE.INVUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
			LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
			WHERE A.INVDATE BETWEEN @sDate_F AND @sDate_T
				AND B.ITEM BETWEEN @sItem_F AND @sItem_T

			UNION ALL

			--Credit/Debit
			SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, (B.EXTCCOST * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) COGS, (B.EXTCRDMISC * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) EXTCRDMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
			FROM OECRDH A
			LEFT OUTER JOIN OECRDD B ON A.CRDUNIQ = B.CRDUNIQ
			LEFT OUTER JOIN OECRDHO ARTYPE ON A.CRDUNIQ = ARTYPE.CRDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
			LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
			WHERE A.CRDDATE BETWEEN @sDate_F AND @sDate_T
				AND B.ITEM BETWEEN @sItem_F AND @sItem_T
		) A
		--LEFT OUTER JOIN #SO SO ON A.ITEM = SO.ITEMNO
		LEFT OUTER JOIN (
			SELECT ITEMNO, SUM(ORDAMT) AS ORDAMT FROM #SO GROUP BY ITEMNO
		) SO ON A.ITEM = SO.ITEMNO
		GROUP BY A.ITEM, A.ARTYPE

		UNION ALL

		--ORDER
		SELECT A.ITEM, SUM(A.ORDAMT) AS ORDAMT, 0 AS COGS, 0 AS INVSUBTOT, 'No' AS AR, A.ARTYPE
		FROM (

			SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTINVMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
			FROM OEORDH A
			LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
			LEFT OUTER JOIN OEORDHO ARTYPE ON A.ORDUNIQ = ARTYPE.ORDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
			LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
			WHERE A.INVSUBTOT <> 0

			UNION ALL

			SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTSHIMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
			FROM OESHIH	A
			LEFT OUTER JOIN OESHID B ON A.SHIUNIQ = B.SHIUNIQ
			LEFT OUTER JOIN OESHIHO ARTYPE ON A.SHIUNIQ = ARTYPE.SHIUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
			LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
			WHERE NUMINVOICE = 0

		) A
		WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
		GROUP BY A.ITEM, A.ARTYPE

	) A
	LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO
	LEFT OUTER JOIN OEMISC MISC ON A.ITEM = MISC.MISCCHARGE
	ORDER BY A.AR DESC, A.ITEM

End
Else
Begin
Select * from 
(

SELECT
ROW_NUMBER() OVER(ORDER BY  A.AR DESC, A.ITEM) AS rownum,
RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], MISC.[DESC])) AS ITEMDESC, SUM(A.ORDAMT) AS ORDAMT, SUM(A.COGS) AS COGS, SUM(A.EXTINVMISC) AS EXTINVMISC, A.AR, A.ARTYPE,
(
Select count(1)
FROM
(
SELECT RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], MISC.[DESC])) AS ITEMDESC, SUM(A.ORDAMT) AS ORDAMT, SUM(A.COGS) AS COGS, SUM(A.EXTINVMISC) AS EXTINVMISC, A.AR, A.ARTYPE
FROM (

	SELECT A.ITEM, SUM(SO.ORDAMT) AS ORDAMT, SUM(A.EXTICOST) AS COGS, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AR, A.ARTYPE
	FROM (

		--Invoice
		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTICOST, B.EXTINVMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OEINVH A
		LEFT OUTER JOIN OEINVD B ON A.INVUNIQ = B.INVUNIQ
		LEFT OUTER JOIN OEINVHO ARTYPE ON A.INVUNIQ = ARTYPE.INVUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.INVDATE BETWEEN @sDate_F AND @sDate_T
			AND B.ITEM BETWEEN @sItem_F AND @sItem_T

		UNION ALL

		--Credit/Debit
		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, (B.EXTCCOST * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) COGS, (B.EXTCRDMISC * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) EXTCRDMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OECRDH A
		LEFT OUTER JOIN OECRDD B ON A.CRDUNIQ = B.CRDUNIQ
		LEFT OUTER JOIN OECRDHO ARTYPE ON A.CRDUNIQ = ARTYPE.CRDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.CRDDATE BETWEEN @sDate_F AND @sDate_T
			AND B.ITEM BETWEEN @sItem_F AND @sItem_T
	) A
	--LEFT OUTER JOIN #SO SO ON A.ITEM = SO.ITEMNO
	LEFT OUTER JOIN (
			SELECT ITEMNO, SUM(ORDAMT) AS ORDAMT FROM #SO GROUP BY ITEMNO
	) SO ON A.ITEM = SO.ITEMNO

	GROUP BY A.ITEM, A.ARTYPE
	
	UNION ALL

	--ORDER
	SELECT A.ITEM, SUM(A.ORDAMT) AS ORDAMT, 0 AS COGS, 0 AS INVSUBTOT, 'No' AS AR, A.ARTYPE
	FROM (

		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTINVMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OEORDH A
		LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
		LEFT OUTER JOIN OEORDHO ARTYPE ON A.ORDUNIQ = ARTYPE.ORDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.INVSUBTOT <> 0

		UNION ALL

		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTSHIMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OESHIH	A
		LEFT OUTER JOIN OESHID B ON A.SHIUNIQ = B.SHIUNIQ
		LEFT OUTER JOIN OESHIHO ARTYPE ON A.SHIUNIQ = ARTYPE.SHIUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE NUMINVOICE = 0

	) A
	WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
	GROUP BY A.ITEM, A.ARTYPE

) A
LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO
LEFT OUTER JOIN OEMISC MISC ON A.ITEM = MISC.MISCCHARGE
GROUP BY A.ITEM, RTRIM(ISNULL(ITEM.[DESC], MISC.[DESC])), A.AR, A.ARTYPE
)a
) cnt
FROM (

	SELECT A.ITEM, SUM(SO.ORDAMT) AS ORDAMT, SUM(A.EXTICOST) AS COGS, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AR, A.ARTYPE
	FROM (
		--Invoice
		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTICOST, B.EXTINVMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OEINVH A
		LEFT OUTER JOIN OEINVD B ON A.INVUNIQ = B.INVUNIQ
		LEFT OUTER JOIN OEINVHO ARTYPE ON A.INVUNIQ = ARTYPE.INVUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.INVDATE BETWEEN @sDate_F AND @sDate_T
			AND B.ITEM BETWEEN @sItem_F AND @sItem_T

		UNION ALL

		--Credit/Debit
		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, (B.EXTCCOST * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) COGS, (B.EXTCRDMISC * CASE WHEN A.ADJTYPE = 1 THEN -1 ELSE 1 END) EXTCRDMISC, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OECRDH A
		LEFT OUTER JOIN OECRDD B ON A.CRDUNIQ = B.CRDUNIQ
		LEFT OUTER JOIN OECRDHO ARTYPE ON A.CRDUNIQ = ARTYPE.CRDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.CRDDATE BETWEEN @sDate_F AND @sDate_T
			AND B.ITEM BETWEEN @sItem_F AND @sItem_T
	) A
	--EFT OUTER JOIN #SO SO ON A.ITEM = SO.ITEMNO
	LEFT OUTER JOIN (
		SELECT ITEMNO, SUM(ORDAMT) AS ORDAMT FROM #SO GROUP BY ITEMNO
	) SO ON A.ITEM = SO.ITEMNO

	GROUP BY A.ITEM, A.ARTYPE

	UNION ALL

	--ORDER
	SELECT A.ITEM, SUM(A.ORDAMT) AS ORDAMT, 0 AS COGS, 0 AS INVSUBTOT, 'No' AS AR, A.ARTYPE
	FROM (

		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTINVMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OEORDH A
		LEFT OUTER JOIN OEORDD B ON A.ORDUNIQ = B.ORDUNIQ
		LEFT OUTER JOIN OEORDHO ARTYPE ON A.ORDUNIQ = ARTYPE.ORDUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE A.INVSUBTOT <> 0

		UNION ALL

		SELECT CASE WHEN B.LINETYPE = 1 THEN B.ITEM ELSE B.MISCCHARGE END ITEM, B.EXTSHIMISC AS ORDAMT, ISNULL(OPT.VDESC, '') AS ARTYPE
		FROM OESHIH	A
		LEFT OUTER JOIN OESHID B ON A.SHIUNIQ = B.SHIUNIQ
		LEFT OUTER JOIN OESHIHO ARTYPE ON A.SHIUNIQ = ARTYPE.SHIUNIQ AND ARTYPE.OPTFIELD = 'SALESTYPE'
		LEFT OUTER JOIN CSOPTFD OPT ON ARTYPE.OPTFIELD = OPT.OPTFIELD AND ARTYPE.[VALUE] = OPT.[VALUE]
		WHERE NUMINVOICE = 0

	) A
	WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
	GROUP BY A.ITEM, A.ARTYPE

) A
LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO
LEFT OUTER JOIN OEMISC MISC ON A.ITEM = MISC.MISCCHARGE
GROUP BY A.ITEM, RTRIM(ISNULL(ITEM.[DESC], MISC.[DESC])), A.AR, A.ARTYPE
)A
Where rownum <= @pageNum * @amount
and rownum >(@pageNum-1) * @amount 
ORDER BY A.AR DESC, A.ITEMNO

End

Go