CREATE PROC [dbo].[SP_PZ3120_Vend_Items]
	@sDate_F  CHAR(8),		-- 매입일자_FROM
	@sDate_T  CHAR(8),		-- 매입일자_TO
	@sItem_F  VARCHAR(24),	-- 품목코드_FROM
	@sItem_T  VARCHAR(24),	-- 품목코드_TO
	@ExcelYN  VARCHAR(1)='N',	
    @pageNum int =1,
    @amount	int =10
AS

CREATE TABLE #PO (
	PORHSEQ	DECIMAL(18, 0),
	ITEMNO	VARCHAR(24),
	POAMT	DECIMAL(18, 3)
)

INSERT INTO #PO (PORHSEQ, ITEMNO, POAMT)
SELECT A.PORHSEQ, B.ITEMNO, (B.EXTENDED + B.EXTRECEIVE) AS ORDAMT
FROM POPORH1 A
LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
WHERE B.PORHSEQ IS NOT NULL



if(@ExcelYN='N')
BEGIN

	SELECT A.*
	FROM (
	
		SELECT RTRIM(A.ITEMNO) AS ITEMNO, RTRIM(ISNULL(A.ITEMDESC, '')) AS ITEMDESC, A.POAMT, A.EXTINVMISC, A.AP,
			ROW_NUMBER() OVER(ORDER BY A.AP DESC, A.ITEMNO) AS rownum,
			( SELECT count(1)
			  FROM (	
			  
					SELECT RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], '')) AS ITEMDESC, A.POAMT, A.EXTINVMISC, A.AP
					FROM (
						SELECT A.ITEM, SUM(PO.POAMT) AS POAMT, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AP
						FROM (
							--Invoice
							SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
							FROM POINVH1 A
							LEFT OUTER JOIN POINVL B ON A.INVHSEQ = B.INVHSEQ		
							WHERE B.INVHSEQ IS NOT NULL
								AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
								AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T

							UNION ALL

							--Credit/Debit
							SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
							FROM POCRNH1 A
							LEFT OUTER JOIN POCRNL B ON A.CRNHSEQ = B.CRNHSEQ
							WHERE B.CRNHSEQ IS NOT NULL
								AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
								AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T
						) A
						LEFT OUTER JOIN #PO PO ON A.PORHSEQ = PO.PORHSEQ AND A.ITEM = PO.ITEMNO
						GROUP BY A.ITEM


						UNION ALL

						--ORDER
						SELECT A.ITEM, SUM(A.POAMT) AS POAMT, 0 AS INVSUBTOT, 'No' AS AP
						FROM (
							SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS POAMT
							FROM POPORH1 A
							LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
							WHERE B.PORHSEQ IS NOT NULL
							UNION ALL
							SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS ORDAMT
							FROM PORCPH1	A
							LEFT OUTER JOIN PORCPL B ON A.RCPHSEQ = B.RCPHSEQ
							WHERE B.PORHSEQ IS NOT NULL AND ISINVOICED = 0
						) A
						WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
						GROUP BY A.ITEM
						HAVING SUM(A.POAMT) <> 0
					) A
					LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO

				)as A
			)as cnt

		FROM (

			SELECT RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], '')) AS ITEMDESC, A.POAMT, A.EXTINVMISC, A.AP
			FROM (
				SELECT A.ITEM, SUM(PO.POAMT) AS POAMT, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AP
				FROM (
					--Invoice
					SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
					FROM POINVH1 A
					LEFT OUTER JOIN POINVL B ON A.INVHSEQ = B.INVHSEQ		
					WHERE B.INVHSEQ IS NOT NULL
						AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
						AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T

					UNION ALL

					--Credit/Debit
					SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
					FROM POCRNH1 A
					LEFT OUTER JOIN POCRNL B ON A.CRNHSEQ = B.CRNHSEQ
					WHERE B.CRNHSEQ IS NOT NULL
						AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
						AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T
				) A
				LEFT OUTER JOIN #PO PO ON A.PORHSEQ = PO.PORHSEQ AND A.ITEM = PO.ITEMNO
				GROUP BY A.ITEM
				
				UNION ALL

				--ORDER
				SELECT A.ITEM, SUM(A.POAMT) AS POAMT, 0 AS INVSUBTOT, 'No' AS AP
				FROM (
					SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS POAMT
					FROM POPORH1 A
					LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
					WHERE B.PORHSEQ IS NOT NULL
					UNION ALL
					SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS ORDAMT
					FROM PORCPH1	A
					LEFT OUTER JOIN PORCPL B ON A.RCPHSEQ = B.RCPHSEQ
					WHERE B.PORHSEQ IS NOT NULL AND ISINVOICED = 0
				) A
				WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
				GROUP BY A.ITEM
				HAVING SUM(A.POAMT) <> 0
			) A
			LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO					   

		) A
	) A
	WHERE rownum <= @pageNum * @amount
	and rownum >(@pageNum-1) * @amount 
	ORDER BY rownum
END
ELSE
BEGIN
	SELECT RTRIM(A.ITEM) AS ITEMNO, RTRIM(ISNULL(ITEM.[DESC], '')) AS ITEMDESC, A.POAMT, A.EXTINVMISC, A.AP
	FROM (
		SELECT A.ITEM, SUM(PO.POAMT) AS POAMT, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AP
		FROM (
			--Invoice
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
			FROM POINVH1 A
			LEFT OUTER JOIN POINVL B ON A.INVHSEQ = B.INVHSEQ		
			WHERE B.INVHSEQ IS NOT NULL
				AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
				AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T

			UNION ALL

			--Credit/Debit
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ISNULL(B.EXTENDED, 0) AS EXTINVMISC
			FROM POCRNH1 A
			LEFT OUTER JOIN POCRNL B ON A.CRNHSEQ = B.CRNHSEQ
			WHERE B.CRNHSEQ IS NOT NULL
				AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
				AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T
		) A
		LEFT OUTER JOIN #PO PO ON A.PORHSEQ = PO.PORHSEQ AND A.ITEM = PO.ITEMNO
		GROUP BY A.ITEM
		
		UNION ALL

		--ORDER
		SELECT A.ITEM, SUM(A.POAMT) AS POAMT, 0 AS INVSUBTOT, 'No' AS AP
		FROM (
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			WHERE B.PORHSEQ IS NOT NULL
			UNION ALL
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, B.EXTENDED AS ORDAMT
			FROM PORCPH1	A
			LEFT OUTER JOIN PORCPL B ON A.RCPHSEQ = B.RCPHSEQ
			WHERE B.PORHSEQ IS NOT NULL AND ISINVOICED = 0
		) A
		WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
		GROUP BY A.ITEM
		HAVING SUM(A.POAMT) <> 0
	) A
	LEFT OUTER JOIN ICITEM ITEM ON A.ITEM = ITEM.FMTITEMNO
	ORDER BY A.AP DESC, A.ITEM
END





Go