CREATE PROC [dbo].[SP_PZ3120_Vend_Items_total]
	@sDate_F  CHAR(8),		-- 매입일자_FROM
	@sDate_T  CHAR(8),		-- 매입일자_TO
	@sItem_F  VARCHAR(24),	-- 품목코드_FROM
	@sItem_T  VARCHAR(24)	-- 품목코드_TO
AS

CREATE TABLE #PO (
	PORHSEQ	DECIMAL(18, 0),
	ITEMNO	VARCHAR(24),
	POAMT	DECIMAL(18, 3)
)

INSERT INTO #PO (PORHSEQ, ITEMNO, POAMT)
SELECT A.PORHSEQ, B.ITEMNO, (B.EXTENDED + B.EXTRECEIVE) AS ORDAMT
FROM POPORH1 A
LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
WHERE B.PORHSEQ IS NOT NULL




BEGIN
	SELECT 
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'Yes' THEN A.EXTINVMISC ELSE 0 END)) AS EXTINVMISC,
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'No' THEN A.POAMT ELSE 0 END)) AS POAMT,
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'Yes' THEN A.EXTINVMISC ELSE A.POAMT END)) AS TOTALAMT
	FROM (
		SELECT A.ITEM, SUM(PO.POAMT) AS POAMT, SUM(A.EXTINVMISC) AS EXTINVMISC, 'Yes' AS AP
		FROM (
			--Invoice
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ROUND(ISNULL(B.EXTENDED, 0) * A.RATE, 0) AS EXTINVMISC
			FROM POINVH1 A
			LEFT OUTER JOIN POINVL B ON A.INVHSEQ = B.INVHSEQ		
			WHERE B.INVHSEQ IS NOT NULL
				AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
				AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T

			UNION ALL

			--Credit/Debit
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, 0 AS POAMT, ROUND(ISNULL(B.EXTENDED, 0) * A.RATE, 0) AS EXTINVMISC
			FROM POCRNH1 A
			LEFT OUTER JOIN POCRNL B ON A.CRNHSEQ = B.CRNHSEQ
			WHERE B.CRNHSEQ IS NOT NULL
				AND A.[DATE] BETWEEN @sDate_F AND @sDate_T
				AND B.ITEMNO BETWEEN @sItem_F AND @sItem_T
		) A
		--LEFT OUTER JOIN #PO PO ON A.PORHSEQ = PO.PORHSEQ AND A.ITEM = PO.ITEMNO
		LEFT OUTER JOIN (
			SELECT ITEMNO, SUM(POAMT) AS POAMT FROM #PO GROUP BY ITEMNO
		) PO ON A.ITEM = PO.ITEMNO
		GROUP BY A.ITEM
		
		UNION ALL

		--ORDER
		SELECT A.ITEM, SUM(A.POAMT) AS POAMT, 0 AS INVSUBTOT, 'No' AS AP
		FROM (
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, ROUND((B.EXTENDED * A.RATE), 0) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			WHERE B.PORHSEQ IS NOT NULL
			UNION ALL
			SELECT A.PORHSEQ, B.ITEMNO AS ITEM, ROUND((B.EXTENDED * A.RATE), 0) AS ORDAMT
			FROM PORCPH1	A
			LEFT OUTER JOIN PORCPL B ON A.RCPHSEQ = B.RCPHSEQ
			WHERE B.PORHSEQ IS NOT NULL AND ISINVOICED = 0
		) A
		WHERE A.ITEM BETWEEN @sItem_F AND @sItem_T
		GROUP BY A.ITEM
		HAVING SUM(A.POAMT) <> 0
	) A

END

GO