CREATE PROC [dbo].[SP_PZ3120_Vend]
	@sDate_F  CHAR(8),		-- 매입일자_FROM
	@sDate_T  CHAR(8),		-- 매입일자_TO
	@sVend_F  VARCHAR(24),	-- 구매처_FROM
	@sVend_T  VARCHAR(24),	-- 구매처_TO
	@ExcelYN  VARCHAR(1)='N'	-- 구매처_TO
   ,@pageNum int =1				
   ,@amount	int =10
AS

IF(@ExcelYN='N')
BEGIN
	SELECT
	*
	FROM
	(
	SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
		A.POAMT, --A.POETAXTOT, A.PONETWTX,
		A.DOCTYPE, A.INVNUMBER, A.INVDATE, A.INVSUBTOT, --A.INVETAXTOT, A.INVNETWTX,
		A.AP,ROW_NUMBER() OVER(ORDER BY A.AP DESC, A.VDCODE, A.PODATE, A.INVDATE) AS rownum
		,
	(
	SELECT COUNT(1)as cnt
	FROM
	(
	SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
		A.POAMT, --A.POETAXTOT, A.PONETWTX,
		A.DOCTYPE, A.INVNUMBER, A.INVDATE, A.INVSUBTOT, --A.INVETAXTOT, A.INVNETWTX,
		A.AP
	FROM (
		--Invoice
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE,
			ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 1 AS DOCTYPE, A.INVNUMBER, A.[DATE] AS INVDATE, A.EXTENDED AS INVSUBTOT, A.TAXAMOUNT AS INVETAXTOT, A.DOCTOTAL AS INVNETWTX, 'Yes' AS AP
		FROM POINVH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--Credit/Debit
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE, ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, CASE WHEN A.TRANSTYPE = 6 THEN 3 ELSE 2 END AS DOCTYPE, A.CRNNUMBER, A.[DATE] AS INVDATE,
			(A.EXTENDED * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS CRDSUBTOT, (A.TAXAMOUNT * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVETAXTOT, (A.DOCTOTAL * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVNETWTX, 'Yes' AS AP
		FROM POCRNH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--PURCHASE ORDER

		SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
			SUM(A.POAMT) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 9 AS DOCTYPE, '' AS INVNUMBER, 0 AS INVDATE, 0 AS INVSUBTOT, 0 AS INVETAXTOT, 0 AS INVNETWTX, 'No' AS AP
		FROM (

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM POPORH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.EXTENDED <> 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

			UNION ALL

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM PORCPH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.ISINVOICED = 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T
		) A
		GROUP BY A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE

	) A 
	)A
	) as cnt


	FROM (
		--Invoice
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE,
			ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 1 AS DOCTYPE, A.INVNUMBER, A.[DATE] AS INVDATE, A.EXTENDED AS INVSUBTOT, A.TAXAMOUNT AS INVETAXTOT, A.DOCTOTAL AS INVNETWTX, 'Yes' AS AP
		FROM POINVH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--Credit/Debit
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE, ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, CASE WHEN A.TRANSTYPE = 6 THEN 3 ELSE 2 END AS DOCTYPE, A.CRNNUMBER, A.[DATE] AS INVDATE,
			(A.EXTENDED * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS CRDSUBTOT, (A.TAXAMOUNT * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVETAXTOT, (A.DOCTOTAL * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVNETWTX, 'Yes' AS AP
		FROM POCRNH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--PURCHASE ORDER

		SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
			SUM(A.POAMT) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 9 AS DOCTYPE, '' AS INVNUMBER, 0 AS INVDATE, 0 AS INVSUBTOT, 0 AS INVETAXTOT, 0 AS INVNETWTX, 'No' AS AP
		FROM (

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM POPORH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.EXTENDED <> 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

			UNION ALL

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM PORCPH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.ISINVOICED = 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T
		) A
		GROUP BY A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE

		) A 
		
	) A
	Where rownum <= @pageNum * @amount
	and rownum >(@pageNum-1) * @amount 
	ORDER BY rownum
	
END
ELSE
BEGIN
	SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
		A.POAMT, --A.POETAXTOT, A.PONETWTX,
		A.DOCTYPE, A.INVNUMBER, A.INVDATE, A.INVSUBTOT, --A.INVETAXTOT, A.INVNETWTX,
		A.AP
	FROM (
		--Invoice
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE,
			ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 1 AS DOCTYPE, A.INVNUMBER, A.[DATE] AS INVDATE, A.EXTENDED AS INVSUBTOT, A.TAXAMOUNT AS INVETAXTOT, A.DOCTOTAL AS INVNETWTX, 'Yes' AS AP
		FROM POINVH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--Credit/Debit
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE, ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, CASE WHEN A.TRANSTYPE = 6 THEN 3 ELSE 2 END AS DOCTYPE, A.CRNNUMBER, A.[DATE] AS INVDATE,
			(A.EXTENDED * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS CRDSUBTOT, (A.TAXAMOUNT * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVETAXTOT, (A.DOCTOTAL * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) AS INVNETWTX, 'Yes' AS AP
		FROM POCRNH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, SUM(A.EXTENDED + A.EXTRECEIVE) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--PURCHASE ORDER

		SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
			SUM(A.POAMT) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 9 AS DOCTYPE, '' AS INVNUMBER, 0 AS INVDATE, 0 AS INVSUBTOT, 0 AS INVETAXTOT, 0 AS INVNETWTX, 'No' AS AP
		FROM (

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM POPORH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.EXTENDED <> 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

			UNION ALL

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, EXTENDED AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM PORCPH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.ISINVOICED = 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T
		) A
		GROUP BY A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE

	) A 
	ORDER BY A.AP DESC, A.VDCODE, A.PODATE, A.INVDATE
END
Go