CREATE PROC [dbo].[SP_PZ3120_Vend_total]
	@sDate_F  CHAR(8),		-- 매입일자_FROM
	@sDate_T  CHAR(8),		-- 매입일자_TO
	@sVend_F  VARCHAR(24),	-- 구매처_FROM
	@sVend_T  VARCHAR(24)	-- 구매처_TO

AS
BEGIN
	SELECT 
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'Yes' THEN A.INVSUBTOT ELSE 0 END)) AS INVSUBTOT,
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'No' THEN A.POAMT ELSE 0 END)) AS POAMT,
		CONVERT(DECIMAL(18, 0), SUM(CASE WHEN A.AP = 'Yes' THEN A.INVSUBTOT ELSE A.POAMT END)) AS TOTALAMT
	FROM (
		--Invoice
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER,ISNULL(PO.PODATE, 0) AS PODATE,
			ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 1 AS DOCTYPE, A.INVNUMBER, A.[DATE] AS INVDATE, ROUND((A.EXTENDED * A.RATE), 0) AS INVSUBTOT, ROUND((A.TAXAMOUNT * A.RATE), 0) AS INVETAXTOT, ROUND((A.DOCTOTAL * A.RATE), 0) AS INVNETWTX, 'Yes' AS AP
		FROM POINVH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, ROUND(SUM((A.EXTENDED + A.EXTRECEIVE) * A.RATE), 0) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--Credit/Debit
		SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, ISNULL(PO.PODATE, 0) AS PODATE, ISNULL(PO.POAMT, 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, CASE WHEN A.TRANSTYPE = 6 THEN 3 ELSE 2 END AS DOCTYPE, A.CRNNUMBER, A.[DATE] AS INVDATE,
			ROUND(((A.EXTENDED * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) * A.RATE), 0) AS CRDSUBTOT, ROUND(((A.TAXAMOUNT * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) * A.RATE), 0) AS INVETAXTOT, ROUND((A.DOCTOTAL * CASE WHEN A.TRANSTYPE = 6 THEN -1 ELSE 1 END) * A.RATE, 0) AS INVNETWTX, 'Yes' AS AP
		FROM POCRNH1 A
		LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
		LEFT OUTER JOIN (
			SELECT A.PONUMBER, A.[DATE] AS PODATE, ROUND(SUM((A.EXTENDED + A.EXTRECEIVE) * A.RATE), 0) AS POAMT
			FROM POPORH1 A
			LEFT OUTER JOIN POPORL B ON A.PORHSEQ = B.PORHSEQ
			GROUP BY A.PONUMBER, A.[DATE]
		) PO ON A.PONUMBER = PO.PONUMBER
		WHERE A.[DATE] BETWEEN @sDate_F AND @sDate_T
			AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

		UNION ALL

		--PURCHASE ORDER

		SELECT A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE,
			SUM(A.POAMT) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX, 9 AS DOCTYPE, '' AS INVNUMBER, 0 AS INVDATE, 0 AS INVSUBTOT, 0 AS INVETAXTOT, 0 AS INVNETWTX, 'No' AS AP
		FROM (

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, ROUND((A.EXTENDED * A.RATE), 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM POPORH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.EXTENDED <> 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T

			UNION ALL

			SELECT A.VDCODE, B.VENDNAME, A.PONUMBER, A.[DATE] AS PODATE, ROUND((A.EXTENDED * A.RATE), 0) AS POAMT, 0 AS POETAXTOT, 0 AS PONETWTX
			FROM PORCPH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.ISINVOICED = 0
				AND A.VDCODE BETWEEN @sVend_F AND @sVend_T
		) A
		GROUP BY A.VDCODE, A.VENDNAME, A.PONUMBER, A.PODATE

	) A 


END

GO