CREATE PROC [dbo].[SP_PZ3120_Vend_Header]
	@sAP		VARCHAR(3),		-- AP처리여부(Yes / No)
	@sDocNo		VARCHAR(22),	-- 문서번호
	@iDocType	SMALLINT		-- 문서유형
AS

IF @sAP = 'Yes'
BEGIN

	IF @iDocType = 1
	BEGIN

		SELECT RTRIM(A.INVNUMBER) AS INVNUMBER, RTRIM(A.VDCODE) AS VDCODE, RTRIM(A.VDNAME) AS VDNAME, RTRIM(A.RCPNUMBER) AS RCPNUMBER, A.[DATE] AS INVDATE,
			RTRIM(B.STCODE) AS [LOCATION], RTRIM(A.DESCRIPTIO) AS DESCRIPTIO, RTRIM(A.REFERENCE) AS REFERENCE
		FROM POINVH1 A
		LEFT OUTER JOIN POINVH2 B ON A.INVHSEQ = B.INVHSEQ
		WHERE A.INVNUMBER = @sDocNo

	END
	ELSE
	BEGIN

		SELECT RTRIM(A.CRNNUMBER) AS INVNUMBER, RTRIM(A.VDCODE) AS VDCODE, RTRIM(A.VDNAME) AS VDNAME, '' AS RCPNUMBER, [DATE] AS INVDATE,
			RTRIM(B.STCODE) AS [LOCATION], RTRIM(A.DESCRIPTIO) AS DESCRIPTIO, RTRIM(A.REFERENCE) AS REFERENCE
		FROM POCRNH1 A
		LEFT OUTER JOIN POCRNH2 B ON A.CRNHSEQ = B.CRNHSEQ
		WHERE A.CRNNUMBER = @sDocNo

	END
END
ELSE
BEGIN

	SELECT RTRIM(A.PONUMBER) AS INVNUMBER, RTRIM(A.VDCODE) AS VDCODE, RTRIM(A.VDNAME) AS VDNAME, '' AS RCPNUMBER, [DATE] AS INVDATE,
		RTRIM(B.STCODE) AS [LOCATION], RTRIM(A.DESCRIPTIO) AS DESCRIPTIO, RTRIM(A.REFERENCE) AS REFERENCE
	FROM POPORH1 A
	LEFT OUTER JOIN POPORH2 B ON A.PORHSEQ = B.PORHSEQ
	WHERE A.PONUMBER = (
		SELECT DISTINCT A.PONUMBER
		FROM (

			SELECT A.PONUMBER
			FROM POPORH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.EXTENDED <> 0
				AND A.PONUMBER = @sDocNo

			UNION ALL

			SELECT A.PONUMBER
			FROM PORCPH1 A
			LEFT OUTER JOIN APVEN B ON A.VDCODE = B.VENDORID
			WHERE A.ISINVOICED = 0 AND A.PONUMBER <> ''
				AND A.PONUMBER = @sDocNo
		) A
	)
	
END
Go